# Generated by Django 5.2.6 on 2025-09-08 23:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='expenditurecategory',
            name='is_global',
        ),
        migrations.RemoveField(
            model_name='incomecategory',
            name='is_global',
        ),
        migrations.AddField(
            model_name='branch',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='managed_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='allocated_funds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('main', 'Main Branch (Enugu)'), ('sub', 'Sub Branch')], default='sub', max_length=10),
        ),
        migrations.AddField(
            model_name='branch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenditurecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expenditurecategory',
            name='scope',
            field=models.CharField(choices=[('main', 'Main Branch Only'), ('sub', 'Sub Branches Only'), ('all', 'All Branches')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='scope',
            field=models.CharField(choices=[('main', 'Main Branch Only'), ('sub', 'Sub Branches Only'), ('all', 'All Branches')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expenditure', 'Expenditure'), ('allocation', 'Fund Allocation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='FundAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.TextField()),
                ('allocated_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allocated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_allocations_made', to='account.branch')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_allocations_received', to='account.branch')),
            ],
            options={
                'ordering': ['-allocated_date'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='fund_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.fundallocation'),
        ),
    ]
