# Generated by Django 5.2.4 on 2025-11-06 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundallocation',
            name='from_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_allocations_made', to='account.branch'),
        ),
        migrations.AlterField(
            model_name='fundallocation',
            name='to_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_allocations_received', to='account.branch'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expenditure', 'Expenditure')], max_length=20),
        ),
    ]
